### ISSUE TITLE
难以分辨舰队状态

### ISSUE THREAD

**Issue by wafer-li** [govizlora/theme-papercyan#1]
See here: https://github.com/poooi/poi/issues/350

**Comment by athtamis** [comment]
+1，只靠数字分辨，还是小字号，还不是粗体，实在是很难一眼区分。

poi内置的未卜先知插件，里面有实心五角星的颜色分辨；
KCV使用实心方块的颜色分辨。
这两种的状态特征都很明显，能够一眼识别。希望能够参照改进下（活动中我就是一直在未卜先知页面看疲劳的）

**Comment by govizlora** [comment]
我的皮肤里没有针对舰队状态做额外定义，目前都是默认的状态，只要poi主程序那边有定义我这边也会更新。目前这问题应该已经解决了。
